// Code generated by go-swagger; DO NOT EDIT.

package spoons

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/xbcsmith/spoon/models"
)

// FindSpoonsHandlerFunc turns a function with the right signature into a find spoons handler
type FindSpoonsHandlerFunc func(FindSpoonsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn FindSpoonsHandlerFunc) Handle(params FindSpoonsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// FindSpoonsHandler interface for that can handle valid find spoons params
type FindSpoonsHandler interface {
	Handle(FindSpoonsParams, *models.Principal) middleware.Responder
}

// NewFindSpoons creates a new http.Handler for the find spoons operation
func NewFindSpoons(ctx *middleware.Context, handler FindSpoonsHandler) *FindSpoons {
	return &FindSpoons{Context: ctx, Handler: handler}
}

/*FindSpoons swagger:route GET /v1/spoons spoons findSpoons

FindSpoons find spoons API

*/
type FindSpoons struct {
	Context *middleware.Context
	Handler FindSpoonsHandler
}

func (o *FindSpoons) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindSpoonsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
