---
swagger: "2.0"
info:
  description: Spoons are Silverware
  title: The spoon application
  version: 0.0.1
consumes:
- application/com.github.xbcsmith.spoon.v1+json
produces:
- application/com.github.xbcsmith.spoon.v1+json
schemes:
- http
- https
# Binds unix socket
#x-schemes:
#- unix
basePath: /api
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-spoon-token
security:
- key: []
paths:
  /v1/spoons:
    get:
      tags:
        - spoons
      operationId: find_spoons
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the spoon operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"

        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - spoons
      operationId: add_spoon
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /v1/spoons/{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      tags:
      - spoons
      operationId: get_spoon
      responses:
        200:
          description: get a spoon operation
          schema:
            $ref: "#/definitions/item"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
      - spoons
      operationId: update_spoon
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/item"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - spoons
      operationId: destroy_spoon
      parameters:
        - type: integer
          format: int64
          name: id
          in: path
          required: true
      responses:
        204:
          description: Deleted
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /healthz/liveness:
    get:
      tags:
        - healthz
      operationId: get_liveness
      responses:
        200:
          description: return the liveness of app
          schema:
            $ref: "#/definitions/liveness"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /healthz/readiness:
    get:
      tags:
        - healthz
      operationId: get_readiness
      responses:
        200:
          description: return the readiness of app
          schema:
            $ref: "#/definitions/readiness"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        404:
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  principal:
    type: string
  liveness:
    type: object
    required:
      - live
    properties:
      live:
        type: boolean
  readiness:
    type: object
    required:
      - ready
    properties:
      ready:
        type: boolean
