// Code generated by go-swagger; DO NOT EDIT.

package spoons

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/xbcsmith/spoon/models"
)

// NewAddSpoonParams creates a new AddSpoonParams object
// with the default values initialized.
func NewAddSpoonParams() *AddSpoonParams {
	var ()
	return &AddSpoonParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddSpoonParamsWithTimeout creates a new AddSpoonParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddSpoonParamsWithTimeout(timeout time.Duration) *AddSpoonParams {
	var ()
	return &AddSpoonParams{

		timeout: timeout,
	}
}

// NewAddSpoonParamsWithContext creates a new AddSpoonParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddSpoonParamsWithContext(ctx context.Context) *AddSpoonParams {
	var ()
	return &AddSpoonParams{

		Context: ctx,
	}
}

// NewAddSpoonParamsWithHTTPClient creates a new AddSpoonParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddSpoonParamsWithHTTPClient(client *http.Client) *AddSpoonParams {
	var ()
	return &AddSpoonParams{
		HTTPClient: client,
	}
}

/*AddSpoonParams contains all the parameters to send to the API endpoint
for the add spoon operation typically these are written to a http.Request
*/
type AddSpoonParams struct {

	/*Body*/
	Body *models.Item

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add spoon params
func (o *AddSpoonParams) WithTimeout(timeout time.Duration) *AddSpoonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add spoon params
func (o *AddSpoonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add spoon params
func (o *AddSpoonParams) WithContext(ctx context.Context) *AddSpoonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add spoon params
func (o *AddSpoonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add spoon params
func (o *AddSpoonParams) WithHTTPClient(client *http.Client) *AddSpoonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add spoon params
func (o *AddSpoonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add spoon params
func (o *AddSpoonParams) WithBody(body *models.Item) *AddSpoonParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add spoon params
func (o *AddSpoonParams) SetBody(body *models.Item) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddSpoonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
