// Code generated by go-swagger; DO NOT EDIT.

package spoons

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDestroySpoonParams creates a new DestroySpoonParams object
// with the default values initialized.
func NewDestroySpoonParams() *DestroySpoonParams {
	var ()
	return &DestroySpoonParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDestroySpoonParamsWithTimeout creates a new DestroySpoonParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDestroySpoonParamsWithTimeout(timeout time.Duration) *DestroySpoonParams {
	var ()
	return &DestroySpoonParams{

		timeout: timeout,
	}
}

// NewDestroySpoonParamsWithContext creates a new DestroySpoonParams object
// with the default values initialized, and the ability to set a context for a request
func NewDestroySpoonParamsWithContext(ctx context.Context) *DestroySpoonParams {
	var ()
	return &DestroySpoonParams{

		Context: ctx,
	}
}

// NewDestroySpoonParamsWithHTTPClient creates a new DestroySpoonParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDestroySpoonParamsWithHTTPClient(client *http.Client) *DestroySpoonParams {
	var ()
	return &DestroySpoonParams{
		HTTPClient: client,
	}
}

/*DestroySpoonParams contains all the parameters to send to the API endpoint
for the destroy spoon operation typically these are written to a http.Request
*/
type DestroySpoonParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the destroy spoon params
func (o *DestroySpoonParams) WithTimeout(timeout time.Duration) *DestroySpoonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the destroy spoon params
func (o *DestroySpoonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the destroy spoon params
func (o *DestroySpoonParams) WithContext(ctx context.Context) *DestroySpoonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the destroy spoon params
func (o *DestroySpoonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the destroy spoon params
func (o *DestroySpoonParams) WithHTTPClient(client *http.Client) *DestroySpoonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the destroy spoon params
func (o *DestroySpoonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the destroy spoon params
func (o *DestroySpoonParams) WithID(id int64) *DestroySpoonParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the destroy spoon params
func (o *DestroySpoonParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DestroySpoonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
