// Code generated by go-swagger; DO NOT EDIT.

package spoons

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/xbcsmith/spoon/models"
)

// NewUpdateSpoonParams creates a new UpdateSpoonParams object
// with the default values initialized.
func NewUpdateSpoonParams() *UpdateSpoonParams {
	var ()
	return &UpdateSpoonParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSpoonParamsWithTimeout creates a new UpdateSpoonParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateSpoonParamsWithTimeout(timeout time.Duration) *UpdateSpoonParams {
	var ()
	return &UpdateSpoonParams{

		timeout: timeout,
	}
}

// NewUpdateSpoonParamsWithContext creates a new UpdateSpoonParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateSpoonParamsWithContext(ctx context.Context) *UpdateSpoonParams {
	var ()
	return &UpdateSpoonParams{

		Context: ctx,
	}
}

// NewUpdateSpoonParamsWithHTTPClient creates a new UpdateSpoonParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateSpoonParamsWithHTTPClient(client *http.Client) *UpdateSpoonParams {
	var ()
	return &UpdateSpoonParams{
		HTTPClient: client,
	}
}

/*UpdateSpoonParams contains all the parameters to send to the API endpoint
for the update spoon operation typically these are written to a http.Request
*/
type UpdateSpoonParams struct {

	/*Body*/
	Body *models.Item
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update spoon params
func (o *UpdateSpoonParams) WithTimeout(timeout time.Duration) *UpdateSpoonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update spoon params
func (o *UpdateSpoonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update spoon params
func (o *UpdateSpoonParams) WithContext(ctx context.Context) *UpdateSpoonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update spoon params
func (o *UpdateSpoonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update spoon params
func (o *UpdateSpoonParams) WithHTTPClient(client *http.Client) *UpdateSpoonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update spoon params
func (o *UpdateSpoonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update spoon params
func (o *UpdateSpoonParams) WithBody(body *models.Item) *UpdateSpoonParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update spoon params
func (o *UpdateSpoonParams) SetBody(body *models.Item) {
	o.Body = body
}

// WithID adds the id to the update spoon params
func (o *UpdateSpoonParams) WithID(id int64) *UpdateSpoonParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update spoon params
func (o *UpdateSpoonParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSpoonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
