apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spoon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spoon.name" . }}
    helm.sh/chart: {{ include "spoon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spoon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spoon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "SPOON_PORT"
            value: "{{ .Values.service.port }}"
          - name: "SPOON_TOKEN"
            value: "{{ .Values.server.x_spoon_token }}"
          - name: "SPOON_HOST"
            value: "{{ .Values.server.host }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/ready
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/healthz/liveness
              port: http
              httpHeaders:
              - name: Content-Type
                value: "{{ .Values.server.content_type }}"
              - name: X-Spoon-Token
                value: "{{ .Values.server.x_spoon_token }}"
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
