// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/xbcsmith/spoon/restapi/operations/spoons"

	handlers "github.com/xbcsmith/spoon/handlers"
	models "github.com/xbcsmith/spoon/models"
)

// NewSpoonAPI creates a new Spoon instance
func NewSpoonAPI(spec *loads.Document) *SpoonAPI {
	return &SpoonAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		SpoonsAddSpoonHandler: spoons.AddSpoonHandlerFunc(func(params spoons.AddSpoonParams, principal *models.Principal) middleware.Responder {
			if err := handlers.AddItem(params.Body); err != nil {
				return spoons.NewAddSpoonDefault(500).WithPayload(&models.Error{Code: 500, Message: swag.String(err.Error())})
			}
			return spoons.NewAddSpoonCreated().WithPayload(params.Body)

		}),
		SpoonsDestroySpoonHandler: spoons.DestroySpoonHandlerFunc(func(params spoons.DestroySpoonParams, principal *models.Principal) middleware.Responder {
			if err := handlers.DeleteItem(params.ID); err != nil {
				return spoons.NewDestroySpoonDefault(500).WithPayload(&models.Error{Code: 500, Message: swag.String(err.Error())})
			}
			return spoons.NewDestroySpoonNoContent()

		}),
		SpoonsFindSpoonsHandler: spoons.FindSpoonsHandlerFunc(func(params spoons.FindSpoonsParams, principal *models.Principal) middleware.Responder {
			mergedParams := spoons.NewFindSpoonsParams()
			mergedParams.Since = swag.Int64(0)
			if params.Since != nil {
				mergedParams.Since = params.Since
			}
			if params.Limit != nil {
				mergedParams.Limit = params.Limit
			}
			return spoons.NewFindSpoonsOK().WithPayload(handlers.AllItems(*mergedParams.Since, *mergedParams.Limit))

		}),
		SpoonsGetSpoonHandler: spoons.GetSpoonHandlerFunc(func(params spoons.GetSpoonParams, principal *models.Principal) middleware.Responder {
			item, err := handlers.GetItem(params.ID)
			if err != nil {
				return spoons.NewGetSpoonDefault(500).WithPayload(&models.Error{Code: 500, Message: swag.String(err.Error())})
			}
			return spoons.NewGetSpoonOK().WithPayload(item)

		}),
		SpoonsUpdateSpoonHandler: spoons.UpdateSpoonHandlerFunc(func(params spoons.UpdateSpoonParams, principal *models.Principal) middleware.Responder {

			if err := handlers.UpdateItem(params.ID, params.Body); err != nil {
				return spoons.NewUpdateSpoonDefault(500).WithPayload(&models.Error{Code: 500, Message: swag.String(err.Error())})
			}
			return spoons.NewUpdateSpoonOK().WithPayload(params.Body)

		}),

		// Applies when the "x-spoon-token" header is set
		KeyAuth: func(token string) (*models.Principal, error) {
			principal, err := handlers.TokenAuth(token)
			if err != nil {
				return nil, errors.New(401, "incorrect api key auth")
			}
			return principal, nil
		},

		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*SpoonAPI Spoons are Silverware */
type SpoonAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/com.github.xbcsmith.spoon.v1+json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/com.github.xbcsmith.spoon.v1+json" mime type
	JSONProducer runtime.Producer

	// KeyAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key x-spoon-token provided in the header
	KeyAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// SpoonsAddSpoonHandler sets the operation handler for the add spoon operation
	SpoonsAddSpoonHandler spoons.AddSpoonHandler
	// SpoonsDestroySpoonHandler sets the operation handler for the destroy spoon operation
	SpoonsDestroySpoonHandler spoons.DestroySpoonHandler
	// SpoonsFindSpoonsHandler sets the operation handler for the find spoons operation
	SpoonsFindSpoonsHandler spoons.FindSpoonsHandler
	// SpoonsGetSpoonHandler sets the operation handler for the get spoon operation
	SpoonsGetSpoonHandler spoons.GetSpoonHandler
	// SpoonsUpdateSpoonHandler sets the operation handler for the update spoon operation
	SpoonsUpdateSpoonHandler spoons.UpdateSpoonHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *SpoonAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SpoonAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SpoonAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SpoonAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SpoonAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SpoonAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SpoonAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SpoonAPI
func (o *SpoonAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.KeyAuth == nil {
		unregistered = append(unregistered, "XSpoonTokenAuth")
	}

	if o.SpoonsAddSpoonHandler == nil {
		unregistered = append(unregistered, "spoons.AddSpoonHandler")
	}

	if o.SpoonsDestroySpoonHandler == nil {
		unregistered = append(unregistered, "spoons.DestroySpoonHandler")
	}

	if o.SpoonsFindSpoonsHandler == nil {
		unregistered = append(unregistered, "spoons.FindSpoonsHandler")
	}

	if o.SpoonsGetSpoonHandler == nil {
		unregistered = append(unregistered, "spoons.GetSpoonHandler")
	}

	if o.SpoonsUpdateSpoonHandler == nil {
		unregistered = append(unregistered, "spoons.UpdateSpoonHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SpoonAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SpoonAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name, scheme := range schemes {
		switch name {

		case "key":

			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.KeyAuth(token)
			})

		}
	}
	return result

}

// Authorizer returns the registered authorizer
func (o *SpoonAPI) Authorizer() runtime.Authorizer {

	return o.APIAuthorizer

}

// ConsumersFor gets the consumers for the specified media types
func (o *SpoonAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/com.github.xbcsmith.spoon.v1+json":
			result["application/com.github.xbcsmith.spoon.v1+json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *SpoonAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/com.github.xbcsmith.spoon.v1+json":
			result["application/com.github.xbcsmith.spoon.v1+json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SpoonAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the spoon API
func (o *SpoonAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SpoonAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/spoons"] = spoons.NewAddSpoon(o.context, o.SpoonsAddSpoonHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/spoons/{id}"] = spoons.NewDestroySpoon(o.context, o.SpoonsDestroySpoonHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/spoons"] = spoons.NewFindSpoons(o.context, o.SpoonsFindSpoonsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/spoons/{id}"] = spoons.NewGetSpoon(o.context, o.SpoonsGetSpoonHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/spoons/{id}"] = spoons.NewUpdateSpoon(o.context, o.SpoonsUpdateSpoonHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SpoonAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SpoonAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SpoonAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SpoonAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
