// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi The spoon application
Spoons are Silverware


    Schemes:
      http
      https
    Host: localhost
    BasePath: /api
    Version: 0.0.1

    Consumes:
    - application/com.github.xbcsmith.spoon.v1+json

    Produces:
    - application/com.github.xbcsmith.spoon.v1+json

swagger:meta
*/
package restapi
